### ISSUE TITLE
release serial pypi version? 

### ISSUE THREAD

**Issue by wxj6000** [dftd3/simple-dftd3#54]
Recently we found `pytorch` pollutes `openmp` symbols. DFTD3 returns wrong results after the pollution. While some packages are not affected. I guess that is because the current pypi version (v1.0.0) is using the recent version (gomp_5.0) of libgomp. It is not an issue with the recent openmp, but it would be convenient to have a serial version at the same time.

https://github.com/pytorch/pytorch/issues/109446#event-11336247829

**Comment by wxj6000** [comment]
And it seems v1.0.0 and v1.1.0 are not available in pypi.

**Comment by awvwgk** [comment]
Not sure what we can do in this case. PyPI doesn't really allow distributing multiple versions of a wheel with different build settings.

One option for addressing this could be to use the [torch version of dftd3](https://github.com/dftd3/tad-dftd3) instead of the regular one. In case there are features missing in the torch version feel free to open a new issue.
